name: dukaan
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_pro: ^1.0.0
  font_awesome_flutter: 8.8.1
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0
  firebase_storage: ^8.1.0
  shared_preferences: ^2.0.6
  image_picker: ^0.7.5+2
  firebase_database: ^6.1.2
  flutter_screenutil: ^5.0.0+2
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_add_cart.png
    - assets/images/ic_discount.png
    - assets/images/promotion_one.png
    - assets/images/promotion_two.png
    - assets/images/promotion__one.png
    - assets/images/promotion_three.png
    - assets/images/ic_app_icon.png
    - assets/images/ic_category_image.png
    - assets/images/empty_shopping_cart_image.png
    - assets/images/empty_shopping_cart.png
    - assets/images/empty_wish_list.png
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
